FROM debian:8

WORKDIR /srv

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y libcurl3 libgeos-c1 && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY ./target/release/osm2mimir \
    ./target/release/cosmogony2mimir \
    ./target/release/bano2mimir \
    ./target/release/openaddresses2mimir \
    /usr/bin/

