FROM rust:1-jessie as builder

WORKDIR /srv/mimirsbrunn

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update \
    && apt-get install -y make libgeos-c1 libssl-dev libgeos-dev git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ADD . ./

RUN cargo build --release

FROM debian:jessie-slim

WORKDIR /srv

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update \
    && apt-get install -y libcurl3 libgeos-c1 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY --from=builder /srv/mimirsbrunn/target/release/osm2mimir /usr/bin/osm2mimir
COPY --from=builder /srv/mimirsbrunn/target/release/cosmogony2mimir /usr/bin/cosmogony2mimir
COPY --from=builder /srv/mimirsbrunn/target/release/bano2mimir /usr/bin/bano2mimir
COPY --from=builder /srv/mimirsbrunn/target/release/openaddresses2mimir /usr/bin/openaddresses2mimir
