name: Master_Packages

on:
  push:
    branches:
      - master

jobs:
  package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - container: navitia/debian8_dev
            rust: "1.66"

          - container: navitia/debian11_dev
            rust: "1.66"

    container: ${{ matrix.container }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # TODO :
      # Remove this step after ES migration 2->7.
      # We need it to make version 2 and 7 coexist.
      # Be careful, binaries will not have the same name !
      - name: Temporary rename binaries with 7
        run: |
          for exec in bragi bano2mimir cosmogony2mimir ctlmimir openaddresses2mimir osm2mimir poi2mimir ntfs2mimir query; do
            sed -i -e "s/^name\s*=\s*\"$exec\"/name = \"${exec}7\"/" Cargo.toml;
          done

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy

      - name: Build package
        run: ./scripts/build_deb.sh ${{ matrix.version }} 7
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: debian-package-master
          path: ./scripts/deb-scratch/*

      - name: slack notification (the job has failed)
        if: failure()
        run: |
          apt-get update
          apt install --yes --force-yes httpie
          echo '{"text":":Warning: Github Actions: build packages for branch master failed ! (https://github.com/hove-io/mimirsbrunn/actions/workflows/master.yml)."}' | http --json POST ${{secrets.SLACK_NAVITIA_AUTOCOMPLETE_TEAM_URL}}
