name: Release_Packages

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
  schedule:
    - cron: '0 2 1 * *'

jobs:

  package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - version: jessie
            packages: pkg-config libssl-dev
            rust: "1.63"

          - version: buster
            packages: pkg-config libssl-dev
            rust: "1.63"


    container: debian:${{matrix.version}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install requirements
        run: |
          apt-get update
          apt-get install --yes --force-yes curl wget build-essential
          apt-get install --yes --force-yes ${{ matrix.packages }}
      # TODO :
      # Remove this step after ES migration 2->7.
      # We need it to make version 2 and 7 coexist.
      # Be careful, binaries will not have the same name !
      - name: Temporary rename binaries with 7
        run: |
          for exec in bragi bano2mimir cosmogony2mimir ctlmimir openaddresses2mimir osm2mimir poi2mimir ntfs2mimir query; do
            sed -i -e "s/^name\s*=\s*\"$exec\"/name = \"${exec}7\"/" Cargo.toml;
          done

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy
      - name: Build package
        run: ./scripts/build_deb.sh ${{ matrix.version }} 7
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: debian-package-release
          path: ./scripts/deb-scratch/*

      - name: Github Release
        uses: softprops/action-gh-release@v1
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: slack notification (the job has failed)
        if: failure()
        run: |
          apt install --yes --force-yes httpie
          echo '{"text":":Warning: Github Actions: build packages for branch release failed  ! (https://github.com/hove-io/mimirsbrunn/actions/workflows/release.yml)."}' | http --json POST ${{secrets.SLACK_NAVITIA_AUTOCOMPLETE_TEAM_URL}}

  publish:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: install  dependency
        run: |
          sudo apt update
          sudo apt install --yes --force-yes httpie

      - name: slack notification (the job succeeded)
        run: |
          version=$(make version)
          echo '{"text":":information_source: Github Actions: build packages for branch release succeded - New packages mimir ' $VERSION 'is available"}' | http --json POST ${{secrets.SLACK_NAVITIA_AUTOCOMPLETE_TEAM_URL}}
